version: '3.9'

services:
  gateway:
    build: ./gateway
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./gateway:/gateway
      - /gateway/node_modules
    environment:
      - PORT=3000
      - HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  users:
    build: ./users
    command: npm run start:dev
    volumes:
      - ./users:/users
      - /users/node_modules
    environment:
      - PORT=6379
      - HOST=redis
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  news:
    build: ./news
    command: npm run start:dev
    volumes:
      - ./news:/news
      - /news/node_modules
    environment:
      - PORT=6379
      - HOST=redis
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
volumes:
  mongo-volume:
  redis-volume: