version: '3.9'

services:
  gateway:
    build: ./gateway
    command: npm run test
    ports:
      - 3000:3000
    depends_on:
      - users
      - news
      - mongodb
    volumes:
      - ./gateway:/gateway
      - /gateway/node_modules
    environment:
      - PORT=3000
      - USERS_SERVICE_PORT=4000
      - USERS_SERVICE_HOST=users
      - NEWS_SERVICE_PORT=4004
      - NEWS_SERVICE_HOST=news
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  users:
    build: ./users
    command: npm run test
    volumes:
      - ./users:/users
      - /users/node_modules
    environment:
      - PORT=4000
      - HOST=users
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  news:
    build: ./news
    command: npm run test
    volumes:
      - ./news:/news
      - /news/node_modules
    environment:
      - PORT=4004
      - HOST=news
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
volumes:
  mongo-volume: