version: '3.9'

services:
  gateway:
    build: ./gateway
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./gateway:/gateway
      - /gateway/node_modules
    environment:
      - PORT=3000
      - NEWS_PORT=5050
      - NEWS_HOST=news
      - USERS_PORT=4040
      - USERS_HOST=users
      - SOCKET_PORT=3030
      - SOCKET_HOST=gateway
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
    depends_on:
      - users
      - news
      - mongodb
  users:
    build: ./users
    command: npm run start:dev
    volumes:
      - ./users:/users
      - /users/node_modules
    environment:
      - PORT=4040
      - HOST=users
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  news:
    build: ./news
    command: npm run start:dev
    volumes:
      - ./news:/news
      - /news/node_modules
    environment:
      - PORT=5050
      - HOST=news
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
volumes:
  mongo-volume: